In [2]:
!pip install SQLAlchemy==1.4.49

Requirement already satisfied: SQLAlchemy==1.4.49 in /usr/local/lib/python3.10/dist-packages (1.4.49)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from SQLAlchemy==1.4.49) (2.0.2)

#Please run this in google colab. Import the stroke_data.sqlite file into the content folder for colab.

In [ ]:
import sqlalchemy
import pandas as pd

from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine

# Database Setup
engine = create_engine("sqlite:////content/stroke_data.sqlite")

# reflect an existing database into a new model
Base = automap_base()

# reflect the tables
Base.prepare(autoload_with=engine)

#test view all classes found by automap
Base.classes.keys()

conn = engine.connect()

#populate stroke data table
stroke_df = pd.read_sql('SELECT * FROM stroke_data', conn)

stroke_df.head()

,?,age,avg_glucose_level,bmi,ever_married_No,ever_married_Yes,work_type_Govt_job,work_type_Private,work_type_Self-employed,work_type_children,Residence_type_Rural,Residence_type_Urban,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes,stroke
0,0,1.040584334185826,2.723410903530197,1.193238162209789,0,1,0,1,0,0,0,1,0,1,0,0,1
1,1,1.614270327485722,-0.0005227665986433442,0.5893896105370293,0,1,0,1,0,0,1,0,0,0,1,0,1
2,2,0.24624988192443203,1.4485291841720218,0.8692218661902591,0,1,0,1,0,0,0,1,0,0,0,1,1
3,3,1.5701406356934222,1.5126504540805694,-0.6624915331747888,0,1,0,0,1,0,1,0,0,0,1,0,1
4,4,1.6584000192780215,1.7808947977464298,0.07390913959686891,0,1,0,1,0,0,0,1,0,1,0,0,1

In [3]:
stroke_df = stroke_df.drop(['?'], axis = 1)
stroke_df.head()

,age,avg_glucose_level,bmi,ever_married_No,ever_married_Yes,work_type_Govt_job,work_type_Private,work_type_Self-employed,work_type_children,Residence_type_Rural,Residence_type_Urban,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes,stroke
0,1.040584334185826,2.723410903530197,1.193238162209789,0,1,0,1,0,0,0,1,0,1,0,0,1
1,1.614270327485722,-0.0005227665986433442,0.5893896105370293,0,1,0,1,0,0,1,0,0,0,1,0,1
2,0.24624988192443203,1.4485291841720218,0.8692218661902591,0,1,0,1,0,0,0,1,0,0,0,1,1
3,1.5701406356934222,1.5126504540805694,-0.6624915331747888,0,1,0,0,1,0,1,0,0,0,1,0,1
4,1.6584000192780215,1.7808947977464298,0.07390913959686891,0,1,0,1,0,0,0,1,0,1,0,0,1

In [29]:
stroke_df = stroke_df.apply(pd.to_numeric, errors='coerce')

In [30]:
from sklearn.model_selection import train_test_split
import tensorflow as tf

In [31]:
y = stroke_df['stroke']
X = stroke_df.drop(columns='stroke')
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [32]:
type(X['ever_married_Yes'][0])

numpy.int64

In [33]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

nn_model = tf.keras.models.Sequential()

# First hidden layer
nn_model.add(tf.keras.layers.Dense(units=8, activation="relu", input_dim=15))

# Second hidden layer
nn_model.add(tf.keras.layers.Dense(units=8, activation="relu"))

# Output layer
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

In [34]:
# Compile the model
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [35]:
# Train the model
fit_model = nn_model.fit(X_train, y_train, epochs=50)

Epoch 1/50
117/117 [==============================] - 1s 2ms/step - loss: 0.4584 - accuracy: 0.9082
Epoch 2/50
117/117 [==============================] - 0s 2ms/step - loss: 0.2194 - accuracy: 0.9518
Epoch 3/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1863 - accuracy: 0.9518
Epoch 4/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1759 - accuracy: 0.9518
Epoch 5/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1692 - accuracy: 0.9518
Epoch 6/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1650 - accuracy: 0.9518
Epoch 7/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1623 - accuracy: 0.9518
Epoch 8/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1604 - accuracy: 0.9518
Epoch 9/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1592 - accuracy: 0.9518
Epoch 10/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1578 - accuracy: 0.9518
Epoch 11/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1577 - accuracy: 0.9518
Epoch 12/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1569 - accuracy: 0.9518
Epoch 13/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1565 - accuracy: 0.9518
Epoch 14/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1561 - accuracy: 0.9518
Epoch 15/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1557 - accuracy: 0.9518
Epoch 16/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1556 - accuracy: 0.9518
Epoch 17/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1553 - accuracy: 0.9518
Epoch 18/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1554 - accuracy: 0.9518
Epoch 19/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1549 - accuracy: 0.9518
Epoch 20/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1545 - accuracy: 0.9518
Epoch 21/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1547 - accuracy: 0.9518
Epoch 22/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1545 - accuracy: 0.9518
Epoch 23/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1542 - accuracy: 0.9518
Epoch 24/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1542 - accuracy: 0.9518
Epoch 25/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1540 - accuracy: 0.9518
Epoch 26/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1537 - accuracy: 0.9518
Epoch 27/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1537 - accuracy: 0.9518
Epoch 28/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1535 - accuracy: 0.9518
Epoch 29/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1534 - accuracy: 0.9518
Epoch 30/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1533 - accuracy: 0.9518
Epoch 31/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1530 - accuracy: 0.9518
Epoch 32/50
117/117 [==============================] - 0s 3ms/step - loss: 0.1528 - accuracy: 0.9518
Epoch 33/50
117/117 [==============================] - 0s 3ms/step - loss: 0.1526 - accuracy: 0.9518
Epoch 34/50
117/117 [==============================] - 0s 3ms/step - loss: 0.1528 - accuracy: 0.9518
Epoch 35/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1528 - accuracy: 0.9518
Epoch 36/50
117/117 [==============================] - 0s 3ms/step - loss: 0.1528 - accuracy: 0.9518
Epoch 37/50
117/117 [==============================] - 0s 3ms/step - loss: 0.1522 - accuracy: 0.9518
Epoch 38/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1525 - accuracy: 0.9518
Epoch 39/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1522 - accuracy: 0.9518
Epoch 40/50
117/117 [==============================] - 0s 3ms/step - loss: 0.1523 - accuracy: 0.9518
Epoch 41/50
117/117 [==============================] - 0s 3ms/step - loss: 0.1521 - accuracy: 0.9518
Epoch 42/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1522 - accuracy: 0.9518
Epoch 43/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1518 - accuracy: 0.9518
Epoch 44/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1519 - accuracy: 0.9518
Epoch 45/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1518 - accuracy: 0.9518
Epoch 46/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1518 - accuracy: 0.9518
Epoch 47/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1520 - accuracy: 0.9518
Epoch 48/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1517 - accuracy: 0.9518
Epoch 49/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1516 - accuracy: 0.9518
Epoch 50/50
117/117 [==============================] - 0s 2ms/step - loss: 0.1518 - accuracy: 0.9518

In [37]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

39/39 - 0s - loss: 0.1694 - accuracy: 0.9454 - 444ms/epoch - 11ms/step
Loss: 0.16939987242221832, Accuracy: 0.9454253315925598